version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
      docker_layer_caching: true    # default - false
    steps:
      - checkout
      - run:
          name: info
          command: |
            whoami
      - run:
          name: work
          command: |
            sudo -E bash ./test.sh